# Handling Multiple Sequence

Link: https://huggingface.co/learn/llm-course/chapter2/5

## Model and Input Sequence

In [10]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = torch.tensor(ids)

In [5]:
model(input_ids)

IndexError: too many indices for tensor of dimension 1

In [6]:
tokenized_inputs = tokenizer(seq, return_tensors='pt')
print(tokenized_inputs['input_ids'])

tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102]])


In [8]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)

input_ids = torch.tensor([ids])
print("Input IDs:", input_ids)

output = model(input_ids)
print("Logits:", output.logits)

Input IDs: tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012]])
Logits: tensor([[-2.7276,  2.8789]], grad_fn=<AddmmBackward0>)


## Batching

In [11]:
batched_ids = [ids, ids]

input_ids_batched = torch.tensor(batched_ids)
print("Input IDs:", input_ids_batched)

output = model(input_ids_batched)
print("Logits:", output.logits)


Input IDs: tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012],
        [ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012]])
Logits: tensor([[-2.7276,  2.8789],
        [-2.7276,  2.8789]], grad_fn=<AddmmBackward0>)


## Padding the inputs

In [12]:
batched_inputs = [
    [200,200,200],
    [200,200]
]

In [14]:
tokenizer.pad_token_id

0

In [13]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

seq_1_ids = [[200,200,200]]
seq_2_ids = [[200,200]]

batched_ids = [
    [200,200,200],
    [200,200, tokenizer.pad_token_id],
]

print(model(torch.tensor(seq_1_ids)).logits)
print(model(torch.tensor(seq_2_ids)).logits)
print(model(torch.tensor(batched_ids)).logits)



We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.


tensor([[ 1.5694, -1.3895]], grad_fn=<AddmmBackward0>)
tensor([[ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)
tensor([[ 1.5694, -1.3895],
        [ 1.3374, -1.2163]], grad_fn=<AddmmBackward0>)


## Attention Masks

In [18]:
attention_masks = [
    [1,1,1],
    [1,1,0],
]

outputs = model(
    torch.tensor(batched_ids), 
    attention_mask=torch.tensor(attention_masks)
)

print(outputs.logits)

tensor([[ 1.5694, -1.3895],
        [ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)
